// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopApp.Data;

#nullable disable

namespace ShopApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250406213019_AddedCartsOrders")]
    partial class AddedCartsOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ShopApp.Entity.Concrete.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(188),
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7454),
                            Description = "Genel kategori",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7457),
                            Name = "Genel",
                            Url = "genel"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7460),
                            Description = "Telefonlar",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7461),
                            Name = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7463),
                            Description = "Elektronik ürünler",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7464),
                            Name = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7465),
                            Description = "Bilgisayarlar",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7466),
                            Name = "Bilgisayar",
                            Url = "bilgisayar"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7468),
                            Description = "Beyaz Eşyalar",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7468),
                            Name = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7470),
                            Description = "Yurt dışından gelen ürünler",
                            IsActive = false,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 78, DateTimeKind.Local).AddTicks(7471),
                            Name = "Yurt Dışı",
                            Url = "yurt-disi"
                        });
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5926),
                            ImageUrl = "1.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5931),
                            Name = "IPhone 14",
                            Price = 59000m,
                            Properties = "Harika bir telefon",
                            Url = "iphone-14"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5938),
                            ImageUrl = "2.png",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5939),
                            Name = "IPhone 14 Pro",
                            Price = 69000m,
                            Properties = "Bu da harika bir telefon",
                            Url = "iphone-14-pro"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5943),
                            ImageUrl = "3.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5944),
                            Name = "Samsung S23",
                            Price = 49000m,
                            Properties = "İdare eder",
                            Url = "samsung-s23"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5948),
                            ImageUrl = "4.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5949),
                            Name = "Xaomi Note 4",
                            Price = 39000m,
                            Properties = "Harika bir telefon",
                            Url = "xaomi-note-4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5952),
                            ImageUrl = "5.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5953),
                            Name = "MacBook Air M2",
                            Price = 52000m,
                            Properties = "M2nin gücü",
                            Url = "macbook-air-m2"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5957),
                            ImageUrl = "6.png",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5958),
                            Name = "MacBook Pro M3",
                            Price = 79000m,
                            Properties = "16 Gb ram",
                            Url = "macbook-pro-m3"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5962),
                            ImageUrl = "7.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5962),
                            Name = "Vestel Çamaşır Makinesi X65",
                            Price = 19000m,
                            Properties = "Akıllı makine",
                            Url = "vestel-camasir-makinesi-x65"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5966),
                            ImageUrl = "8.png",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(5967),
                            Name = "Arçelik Çamaşır Makinesi A-4",
                            Price = 21000m,
                            Properties = "Süper hızlı makine",
                            Url = "arcelik-camasir-makinesi-a-4"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(6597),
                            ImageUrl = "9.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(6600),
                            Name = "Hoop Dijital Radyo X96",
                            Price = 1250m,
                            Properties = "Klasik radyo keyfi",
                            Url = "hoop-dijital-radyo-x96"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(6605),
                            ImageUrl = "10.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(6606),
                            Name = "Xaomi Dijital Baskül",
                            Price = 2100m,
                            Properties = "Kilonuzu kontrol edin",
                            Url = "xaomi-dijital-baskul"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(6610),
                            ImageUrl = "11.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 4, 7, 0, 30, 15, 79, DateTimeKind.Local).AddTicks(6611),
                            Name = "Blaupunkt AC69 Led TV",
                            Price = 9800m,
                            Properties = "Android tv",
                            Url = "blaupunkt-ac69-led-tv"
                        });
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.CartItem", b =>
                {
                    b.HasOne("ShopApp.Entity.Concrete.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopApp.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.OrderItem", b =>
                {
                    b.HasOne("ShopApp.Entity.Concrete.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopApp.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.Product", b =>
                {
                    b.HasOne("ShopApp.Entity.Concrete.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
