// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopApp.Data;

#nullable disable

namespace ShopApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2611),
                            Description = "Genel kategori",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2626),
                            Name = "Genel",
                            Url = "genel"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2630),
                            Description = "Telefonlar",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2630),
                            Name = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2632),
                            Description = "Elektronik ürünler",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2633),
                            Name = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2635),
                            Description = "Bilgisayarlar",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2635),
                            Name = "Bilgisayar",
                            Url = "bilgisayar"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2637),
                            Description = "Beyaz Eşyalar",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2638),
                            Name = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2639),
                            Description = "Yurt dışından gelen ürünler",
                            IsActive = false,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 372, DateTimeKind.Local).AddTicks(2640),
                            Name = "Yurt Dışı",
                            Url = "yurt-disi"
                        });
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9858),
                            ImageUrl = "1.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9859),
                            Name = "IPhone 14",
                            Price = 59000m,
                            Properties = "Harika bir telefon",
                            Url = "iphone-14"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9865),
                            ImageUrl = "2.png",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9866),
                            Name = "IPhone 14 Pro",
                            Price = 69000m,
                            Properties = "Bu da harika bir telefon",
                            Url = "iphone-14-pro"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9870),
                            ImageUrl = "3.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9871),
                            Name = "Samsung S23",
                            Price = 49000m,
                            Properties = "İdare eder",
                            Url = "samsung-s23"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9875),
                            ImageUrl = "4.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9876),
                            Name = "Xaomi Note 4",
                            Price = 39000m,
                            Properties = "Harika bir telefon",
                            Url = "xaomi-note-4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9880),
                            ImageUrl = "5.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9881),
                            Name = "MacBook Air M2",
                            Price = 52000m,
                            Properties = "M2nin gücü",
                            Url = "macbook-air-m2"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9885),
                            ImageUrl = "6.png",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9886),
                            Name = "MacBook Pro M3",
                            Price = 79000m,
                            Properties = "16 Gb ram",
                            Url = "macbook-pro-m3"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9890),
                            ImageUrl = "7.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9891),
                            Name = "Vestel Çamaşır Makinesi X65",
                            Price = 19000m,
                            Properties = "Akıllı makine",
                            Url = "vestel-camasir-makinesi-x65"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9894),
                            ImageUrl = "8.png",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9895),
                            Name = "Arçelik Çamaşır Makinesi A-4",
                            Price = 21000m,
                            Properties = "Süper hızlı makine",
                            Url = "arcelik-camasir-makinesi-a-4"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9899),
                            ImageUrl = "9.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9900),
                            Name = "Hoop Dijital Radyo X96",
                            Price = 1250m,
                            Properties = "Klasik radyo keyfi",
                            Url = "hoop-dijital-radyo-x96"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9904),
                            ImageUrl = "10.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9905),
                            Name = "Xaomi Dijital Baskül",
                            Price = 2100m,
                            Properties = "Kilonuzu kontrol edin",
                            Url = "xaomi-dijital-baskul"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9909),
                            ImageUrl = "11.png",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2025, 3, 14, 0, 39, 31, 379, DateTimeKind.Local).AddTicks(9910),
                            Name = "Blaupunkt AC69 Led TV",
                            Price = 9800m,
                            Properties = "Android tv",
                            Url = "blaupunkt-ac69-led-tv"
                        });
                });

            modelBuilder.Entity("ShopApp.Entity.Concrete.Product", b =>
                {
                    b.HasOne("ShopApp.Entity.Concrete.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
